# Generated by Django 5.1.7 on 2025-03-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_location_folder_name_project_parent_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
