# Generated by Django 5.1.7 on 2025-03-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_name_alter_project_parent_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_url',
            field=models.CharField(max_length=255),
        ),
    ]
