# Generated by Django 5.1.7 on 2025-04-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_name_alter_project_parent_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='parent_url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('project', 'folder_name')},
        ),
    ]
