# Generated by Django 5.1.7 on 2025-04-12 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_remove_typeannotation_parameter_and_more'),
        ('project', '0011_alter_location_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='parent_url',
            new_name='root_path',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
