# Generated by Django 5.1.7 on 2025-04-12 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('monitoring', '0011_remove_typeannotation_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofolder',
            name='sampling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='monitoring.sampling'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='detection.audiofolder'),
        ),
        migrations.AddField(
            model_name='featureannotationaudio',
            name='annotation_audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='detection.annotationaudio'),
        ),
        migrations.AddField(
            model_name='featureannotationaudio',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='detection.feature'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='type_annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_annotations', to='detection.typeannotation'),
        ),
    ]
