# Generated by Django 5.1.7 on 2025-03-24 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='sample',
        ),
        migrations.AddField(
            model_name='sample',
            name='audio_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='monitoring.audiofile'),
        ),
    ]
