# Generated by Django 5.1.7 on 2025-03-28 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_sample_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='detection',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='specie',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='monitoring.sample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='second_end',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='second_start',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='monitoring.parameter')),
            ],
        ),
        migrations.AddField(
            model_name='detection',
            name='parameters',
            field=models.ManyToManyField(related_name='detections', to='monitoring.parameter'),
        ),
        migrations.AddField(
            model_name='samplevariable',
            name='unit_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sample_variables', to='monitoring.unitmeasure'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pulse',
        ),
        migrations.DeleteModel(
            name='Specie',
        ),
    ]
