# Generated by Django 5.1.7 on 2025-03-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_parameter_unitmeasure_remove_detection_pulse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmeasure',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
