# Generated by Django 5.1.7 on 2025-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_unitmeasure_name_alter_variable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file_path',
            field=models.FileField(upload_to='audio_files/'),
        ),
    ]
