# Generated by Django 5.1.7 on 2025-04-04 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_audiofile_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='parameters',
        ),
        migrations.RenameModel(
            old_name='Parameter',
            new_name='Annotation',
        ),
        migrations.CreateModel(
            name='TypeAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_annotations', to='monitoring.annotation')),
            ],
        ),
        migrations.AddField(
            model_name='detection',
            name='type_annotations',
            field=models.ManyToManyField(related_name='detections', to='monitoring.typeannotation'),
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
