# Generated by Django 5.1.7 on 2025-04-10 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_remove_detection_parameters_and_more'),
        ('project', '0009_alter_location_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='monitoring.sample'),
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='project.location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='monitoring.folders')),
            ],
        ),
        migrations.AddField(
            model_name='audiofile',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='monitoring.folders'),
        ),
    ]
