# Generated by Django 5.1.7 on 2025-04-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_audiofile_sample_folders_audiofile_folder'),
        ('project', '0010_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='project.folder'),
        ),
        migrations.DeleteModel(
            name='Folders',
        ),
    ]
