# Generated by Django 5.1.7 on 2025-04-12 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_remove_audiofile_file_path_audiofile_file_name'),
        ('project', '0011_alter_location_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeannotation',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='type_annotations',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='samplevariable',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='samplevariable',
            name='unit_measure',
        ),
        migrations.RemoveField(
            model_name='samplevariable',
            name='variable',
        ),
        migrations.CreateModel(
            name='Sampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='project.location')),
            ],
        ),
        migrations.CreateModel(
            name='SamplingVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_value', models.FloatField()),
                ('sampling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_variables', to='monitoring.sampling')),
                ('unit_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_variables', to='monitoring.unitmeasure')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_variables', to='monitoring.variable')),
            ],
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='TypeAnnotation',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='SampleVariable',
        ),
    ]
