services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ..:/workspace:cached
  
  db:
    image: postgis/postgis:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=batmonitoring
    ports:
      - 5432:5432   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: